services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    networks:
      - sit
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo
  reservations:
    image: asia-east1-docker.pkg.dev/sleepr-386417/reservations/production
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
    networks:
      - sit
  auth:
    image: asia-east1-docker.pkg.dev/sleepr-386417/auth/production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
    networks:
      - sit
  payments:
    image: asia-east1-docker.pkg.dev/sleepr-386417/payments/production
    env_file:
      - ../apps/payments/.env
    ports:
      - '3003:3003'
    networks:
      - sit
  notifications:
    image: asia-east1-docker.pkg.dev/sleepr-386417/notifications/production
    env_file:
      - ../apps/notifications/.env
    ports:
      - '3004:3004'
    networks:
      - sit
  mongo:
    image: mongo
    networks:
      - sit

networks:
  sit:
    name: sit