apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
      - image: asia-east1-docker.pkg.dev/sleepr-386417/reservations/production
        name: reservations
        env:
         - name: MONGO_URI
           valueFrom:
             secretKeyRef:
                name: mongodb
                key: connectionString