apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
        - image: 579292487711.dkr.ecr.ap-northeast-1.amazonaws.com/reservations:latest
          name: reservations
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
            - name: PORT
              value: "3004"
            - name: AUTH_HOST
              value: auth-tcp
            - name: AUTH_PORT
              value: "3002"
            - name: PAYMENT_HOST
              value: payments
            - name: PAYMENT_PORT
              value: "3001"
          ports:
            - containerPort: 3004
         